version: '3.8'
volumes:
  db-store:
    driver: local
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ..:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-ambassador}
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASS:-root}
    ports:
      - 8080:8080
    networks:
      - app-network
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - 13306:3306
    volumes:
      #- ../db:/var/lib/mysql
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-ambassador}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 4848:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
