version: '3.9'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ..:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-ambassador}
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASS:-root}
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME:-ambassador}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
    volumes:
      - ../dbdata:/var/lib/mysql
    ports:
      - 33066:3306      
      
